version: "2"
services:
  pg:
    image: postgres:13.3
    container_name: pg
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
  web:
          image: yyakovlevaleksandr/market
          depends_on: 
                  - pg
          ports:
                  - 80:8080
          environment:
                  - SPRING_DATASOURCE_URL=jdbc:postgresql://pg:5432/postgres
